name: myArXiv
on:
  workflow_dispatch:
  schedule:
  #https://jasonet.co/posts/scheduled-actions/
  #       ┌───────────── minute (0 - 59)
  #       │ ┌───────────── hour (0 - 23)
  #       │ │ ┌───────────── day of the month (1 - 31)
  #       │ │ │ ┌───────────── month (1 - 12)
  #       │ │ │ │ ┌───────────── day of the week (0 - 6) Sun-Mon...Sat
  #       │ │ │ │ │
  #       │ │ │ │ │
  #       │ │ │ │ │
  #       *  **
  - cron: '0 4 * * 1-5' 
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: execute py script
      run: python crosslist.py 
      
    - name: commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add arxiv_papers.html
        git commit -m "new run happened" -a || true
        
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 
        
    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/${{ github.repository }}.git --branch gh-pages --single-branch gh-pages || git clone https://github.com/${{ github.repository }}.git gh-pages
        cp -r arxiv_papers.html gh-pages/index.html  # Copy your generated file as index.html
        cd gh-pages
        git checkout gh-pages 2>/dev/null || git checkout --orphan gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0  # Use same version as above
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
